### PR TITLE
UX and bug fixes for PayPal checkout

### LINKED ISSUE #19: Incomplete UI with misconfigured paypal
If payment methods are partially configured, but the credentials are incorrect or not supplied - the checkout will contain empty payment methods, with no explanations.  

reaction___example_product

The dashboard / settings should also contain feedback for packages that have errors/missing configurations.

### PR DESCRIPTION
**Pull request by mikemurray**
resolves #19

## Issue #19
Misconfigured PayPal express leaves blank container with everyone shrugging...  ¯\_(ツ)_/¯

### How it was fixed:
Added a check to verify that the required fields to set up PayPal Express are not blank.

---

## Issue (discovered and related to #19)
Paypal Express button disappears on subsequent visits to checkout page.

### Steps to reproduce:
1. Add and item to your cart and checkout
2. Enter all information up to the payment from. Do not submit payment.
3. Click "REACTION" or otherwise navigate away to another page
4. Checkout again without adding any items to your cart (click cart icon, then checkout)
5. PayPal Express checkout button is gone!

### Why its happening:
When you configure PayPal express, it injects a button in a specified container. This can only be done once per physical page (in the traditional full page load sense). 

When you navigate to the checkout page more than once per hard refresh, the PayPal Express configuration (already set up and in memory) throws an error in the console, and essentially ignores the request for setup.

This results in the button needed to initiate the express checkout not being added the the page in the specified container.

### How it was fixed:
Added custom PayPal express button to overcome issues with the checkout button disappearing. Using standard Meteor templates and events, this button will trigger the express checkout.

### CODE REVIEW

File: client/templates/checkout/checkoutButton.js [hunk 1]
```diff
@@ -1,45 +1,118 @@
...
+function doSetup(element, expressCheckoutSettings) {
+  Session.set("paypalExpressSetup", true);
+  const result =  paypal.checkout.setup(expressCheckoutSettings.merchantId, {
+    environment: expressCheckoutSettings.mode,
+    button: element,
+     // Blank function to disable default paypal onClick functionality
+    click: function () {}
+  });
+
+  console.log("Express checkoit result", result);
```
Comment (zenweasel) [inline client/templates/checkout/checkoutButton.js]: Should be removed?

Comment (mikemurray) [inline client/templates/checkout/checkoutButton.js]: done!

**Comment by aaronjudd** [comment]
Merge it.
